def slave_init(port:int=502):
    ...

def slave_start():
    ...

def slave_mapping(start:int,size:int,rw:bool,bits:int)->int:
    ...

def slave_read_to(dest: memoryview,mask: memoryview):
    ...
    
def slave_write_from(src: memoryview,mask: memoryview):
    ...
    
def slave_stop():
    ...
    
def slave_shutdown():
    ...
    
